---
title: "Simulation Study 1 Protocol"
---

## Research Question:

At implementation, how does missing data impact different sample sizes at low outcome prevalance rates?

## Aims:

1.  To determine the impact of missing data in one of five collected continuous variables in a logistic regression model

2.  To investigate methods for handling missing data applied at deployment and how that may affect the precision of the model

3.  To attain convergence at decreasing levels of prevalence

## Data-generating mechanisms

I will develop a CPM based on logistic regression to model the binary outcome Y with five continuous predictors X~1~ -X~5.~ The binary outcome Y is always observed. One predictor, X~1~ is partially observed depending on the mechanism for missing data (i.e., the probability X~1~ is missing). The remaining predictors (X~2~ - X~5~) are fully observed.

Data will be generated to create a development dataset to build the CPM (fully observed). The second dataset will represent a validation study and implementation dataset. All datasets will be generated with N~sim~ = 100,000. The prevalence of Y will be fixed at 50% and decreased to 25%, 10% and 1%. Each simulated data generating mechanism will be repeated for 200 per simulation scenario (per combination of each parameter). Predictors X~1~ -X~5~ will be generated from a standard normal distribution. Missingness will be increased across 25%, 50% and 75%. The effect of variables on the probability of missingness will be fixed at 0 for all predictors except X~2~ which is fixed at 0.5.

\# Table 1: Notation of Simulation Study

+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+
| Parameter   | Description                                                                                                                                                                                                                                                                  | Values                                                                                  |
+=============+==============================================================================================================================================================================================================================================================================+=========================================================================================+
| Outcome     | Binary Outcome $Y$ that is always observed                                                                                                                                                                                                                                   | Prevalence varied at $1$%, $5$% and $10$%                                               |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+
| Predictors  | Five predictors $X_1$, $X_2$, $X_3$, $X_4$, $X_5$ where one predictor $X_1$ is partially observed                                                                                                                                                                            | Predictors are generated from normal distribution                                       |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+
| Model       | Logistic regression model \$P\[Y=1\] = \text{Binom}(\text{expit}(\gamma\*0 +\* \gamma{X1} X_1 + \gamma\*{X2} X_2 +\* \gamma{X3} X_3 + \gamma\*{X4} X_4 +\* \gamma{X5} X_5 + \gamma\_{U}\$ \| $\gamma_{X_1}, \gamma_{X_2}, \gamma_{X_3}, \gamma_{X_4}, \gamma_{X_5} = 0.5$ \| |                                                                                         |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+
| Missingness | The probability missingness in $X_1$                                                                                                                                                                                                                                         | Missingness is varied at $25$% $50$% and $75$% where $\beta_{X_2} = 0.5$ under MAR and, |
|             |                                                                                                                                                                                                                                                                              |                                                                                         |
|             | $P[R=1] = \text{Binom}(\text{expit}(\beta_0 + \beta_{X1} X_1 + \beta_{X2} X_2 + \beta_{X3} X_3 + \beta_{X4} X_4 + \beta_{X5} X_5 + \beta_{U}U))$                                                                                                                             | $\beta_{X_1}$, $\beta_{X_2}$, $\beta_{U}$ = $0.5$ under MNAR                            |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+
| Sample size | Validation sample size always equals development sample size                                                                                                                                                                                                                 | $$ N_{\text{val}}, N_{\text{dev}} = 500; 10,000; 100,000 $$                             |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+
