project:
  type: book
  
book: 
  title: "Results from Simulation Study"
  author: "Mae Chester-Jones"
  chapters: 
  #  - text: "Front Page"
    - file: "index.qmd"
    - file: "01-Protocol1.qmd"
    - file: "02-Results1-MCAR-500.qmd"
    - file: "03-Results1-MCAR-10000.qmd"
    - file: "04-Results1-MCAR-100000.qmd"
    - file: "05-Results1-MAR-500.qmd"
    - file: "06-Results1-MAR-10000.qmd"
    - file: "07-Results1-MAR-100000.qmd"
    - file: "08-Results1-MNAR-500.qmd"
    - file: "09-Results1-MNAR-10000.qmd"
    - file: "10-Results1-MNAR-100000.qmd"

  sidebar: 
    style: "docked"
  
format: 
  html: default
  
editor: visual
